name: fitness_app_nodejs
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.40.0
  table_calendar: ^3.0.6
  get: ^4.6.5
  animated_text_kit: ^4.2.0
  animations: ^2.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Asset Configuration
  assets:
    - lib/assets/images/coach.png
    - lib/assets/images/background.jpg
    - lib/assets/images/login.png
    - lib/assets/images/signup.png
    - lib/assets/images/male.png
    - lib/assets/images/female.png
    - lib/assets/images/looseweight.png
    - lib/assets/images/buildmuscel.png
    - lib/assets/images/keepfit.png
    - lib/assets/images/breath.png
    - lib/assets/images/pullup.png
    - lib/assets/images/situp.png
    - lib/assets/images/pushups.png
    - lib/assets/images/bicepsCurl.png
    - lib/assets/images/leg.png
    - lib/assets/images/plank.png
    - lib/assets/images/strength.png
    - lib/assets/images/yoga.png
    - lib/assets/images/hiit.png
    - lib/assets/images/cardio.png
    - lib/assets/images/core.png
    - lib/assets/images/stretch.png
    - lib/assets/images/pushupchallenge.png
   
    
